# Frozen-threshold evaluation config for Stage 4 (lock results)

evaluation:
  batch_size: 8
  max_samples: null
  save_predictions: true

  threshold:
    mode: file
    # Reuse the Stage 3 champion's threshold via its stable symlink.
    # The symlink is maintained by batch_encoder_training.slurm after each run.
    file: "models/experiments/encoder/codet5p_220m_final_sweep_latest/threshold_sweep_results.json"

  test_sets:
    combined: "data/processed/test.jsonl"
    technologies:
      chef: "data/processed/chef/chef_test.jsonl"
      ansible: "data/processed/ansible/ansible_test.jsonl"
      puppet: "data/processed/puppet/puppet_test.jsonl"

  output_dir: "results/experiments/evaluation/threshold_frozen"

  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - confusion_matrix
    - per_smell_metrics

models:
  encoder:
    path: "models/experiments/encoder/_threshold_placeholder_"
    batch_size: 8

batch_evaluation:
  job_spacing_seconds: 1
