approach: encoder
model_name: microsoft/codebert-base
train_path: data/processed/chef/chef_train.jsonl
val_path: data/processed/chef/chef_val.jsonl
output_dir: test_output
batch_size: 2
learning_rate: 2.0e-05
num_epochs: 1
warmup_steps: 10
save_steps: 50
eval_steps: 25
tokenizers_parallelism: 'false'
