# Encoder Model Configuration
model_name: "microsoft/codebert-base"
max_length: 256
batch_size: 8
learning_rate: 2e-5
num_epochs: 3
warmup_steps: 100
eval_steps: 50
save_steps: 100

# Data paths (will be overridden by CLI args)
train_path: "data/processed/chef_train.jsonl"
val_path: "data/processed/chef_val.jsonl"
output_dir: "models/encoder"

# Training arguments
evaluation_strategy: "steps"
save_strategy: "steps"
logging_steps: 10
load_best_model_at_end: true
metric_for_best_model: "f1"
greater_is_better: true
