# Evaluation configuration for IaC security smell detection models

# Core evaluation settings
evaluation:
  # Global settings
  batch_size: 4
  max_samples: null # null for full dataset, set number for testing
  save_predictions: true

  # Data configuration
  test_path: "data/processed/chef_test.jsonl"
  output_dir: "results/experiments/evaluation"

  # Metrics to compute
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - confusion_matrix
    - per_smell_metrics

# Model configurations
models:
  generative:
    path: "models/generative_latest"
    batch_size: 1 # Smaller batch size for large generative models
    use_4bit: true
    max_new_tokens: 10
  encoder:
    path: "models/encoder_latest"
    batch_size: 8 # Larger batch size for smaller encoder models

# Output configuration
output:
  # Report generation
  reports:
    html: true
    json: true

  # Visualization settings
  plots:
    performance_comparison: true
    confusion_matrices: true
    radar_chart: true
