# Batch evaluation configuration for encoder models

# Batch processing settings
batch_evaluation:
  job_spacing_seconds: 1 # Spacing between job submissions to avoid SLURM overload

# Encoder model evaluation settings
encoder_evaluation:
  # Global evaluation settings
  batch_size: 8 # Default batch size for encoder models
  max_samples: null # null for full dataset, set number for testing
  save_predictions: true

# Data configuration
data:
  test_path: "data/processed/chef_test.jsonl"
